use different icon when station is full
tomekz/viennaBike-native pull request #6
Opened 2018-05-05 20:04 UTC by myin142

I think this feature might be useful if you want to know if there is space left in a station without always clicking on the icon. At least for me it would be very helpful. I have also read some reviews on the play store that want this feature.

2018-05-07 12:12 UTC, tomekz requested changes
Hey, first of all thanks for your very useful contribution !
In general all looks good,  I like the new icons and have only small refactoring request you'll find in the comments.

2018-05-07 12:12 UTC, tomekz commented on src/components/Plan.js
> +              image = {station.free_bikes == 0 ? require('../../assets/img/bikes_empty.png')
The nested ternary is not very readable. There is even a [ESLint rule for that](https://eslint.org/docs/rules/no-nested-ternary) 
I would suggest to extract the logic to a seperate function on the same component level and use simply if blocks

2018-05-07 12:12 UTC, tomekz commented on src/components/StationCard.js
> +              source = {station.free_bikes == 0 ? require('../../assets/img/bikes_empty.png')
Same bout the nestet ternaries here

2018-05-07 12:40 UTC, myin142 commented
I have now moved it to a separate function.

2018-05-08 05:41 UTC, tomekz approved these changes

2018-05-08 05:43 UTC, merged